### ISSUE TITLE
Updating training, validation and testing set for a new LLM

### ISSUE THREAD

**Issue by FireShadow05** [pasquini-dario/LLM_NeuralExec#1]
A helpful addition to facilitate users in testing Neural Exec on other white-box LLMs not currently included could be a simple Python script. This script would update the target prompts for existing training, testing, and validation sets for an LLM that is not already part of the system. 

I am interested in contributing to this issue.

**Comment by pasquini-dario** [comment]
Hello,

sure. I think that the script ```./add_llm_to_dataset.py```  does what you want (sorry for the lack of documentation). Essentially, given a LLM, it adds new targets to the training, validation and testing sets.  Although, the new LLM must be defined and added as in ```./NeuralExec/llm.py```. I am available to give you more info/help you if needed.

**Comment by FireShadow05** [comment]
Thanks for clarifying. Actually I had forked the earlier version of the repo hence I didn't notice the updated script.
