### ISSUE TITLE
No logs for Llama3-8b

### ISSUE THREAD

**Issue by kristian-georgiev** [pasquini-dario/LLM_NeuralExec#3]
Thanks for the great repo! I'm trying to run the `eval_prompt_injection.ipynb` notebook, but it seems like the file `./logs/15_5_llama3_8b_sem` does not exist. Where can I find the logs for Llama3-8b?

**Comment by pasquini-dario** [comment]
sure. My bad. It's in logs now. Let me know if it works.

**Comment by kristian-georgiev** [comment]
All good, thanks!
